version: "3.3"

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_USER=root
      - MYSQL_PASSWORD=eldudeH.22 # pragma: allowlist secret
      - MYSQL_ROOT_PASSWORD=eldudeH.22 # pragma: allowlist secret
    volumes:
      - ./db:/config
    restart: unless-stopped
  docker-rolling-avg:
    container_name: docker-rolling-avg #rolling average container
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-rolling-avg
    volumes:
      - ./result:/result
